//! C emit helpers.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use quintra_content::Registry;

pub fn write_stub_header(out_dir: &Path, reg: &Registry) -> Result<()> {
    let path = out_dir.join("content_stubs.h");
    let body = format!(
        "// Auto-generated by quintra-codegen — Phase 1 stub.\n\
         // Counts (will be replaced by real tables in Phase 2):\n\
         #ifndef QUINTRA_CONTENT_STUBS_H\n\
         #define QUINTRA_CONTENT_STUBS_H\n\
         #define N_CLASSES        {n_classes}\n\
         #define N_ITEMS          {n_items}\n\
         #define N_ENEMIES        {n_enemies}\n\
         #define N_BIOMES         {n_biomes}\n\
         #define N_ROOM_TEMPLATES {n_rooms}\n\
         #endif\n",
        n_classes = reg.n_classes(),
        n_items   = reg.n_items(),
        n_enemies = reg.n_enemies(),
        n_biomes  = reg.n_biomes(),
        n_rooms   = reg.n_room_templates(),
    );
    fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;
    Ok(())
}
