//! C emit — translates the validated `Registry` into GBDK-compatible C tables.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use quintra_content::{
    AiScriptId, BaseStats, Class, DoorMask, Effect, Enemy, EnemyStats, FormTheme,
    Item, ItemKind, ProjectileKind, Rarity, Registry, RoomKind, RoomSize, RoomTemplate,
    ScreenCellKind, ShotPattern, SpawnRole, SpawnSlot, Status, Stat, Trigger,
    ZeldaOverworldBiome,
};

const HEADER_NOTE: &str =
    "// AUTO-GENERATED BY quintra-codegen — DO NOT EDIT BY HAND.\n\
     // Source: content/src/. Regenerate via `cargo run -p quintra-codegen`.\n\n";

pub fn write_all(out: &Path, reg: &Registry) -> Result<()> {
    write_enums(out)?;
    write_classes(out, reg)?;
    write_items(out, reg)?;
    write_enemies(out, reg)?;
    write_biomes(out, reg)?;
    write_zelda_overworld(out, reg)?;
    write_rooms(out, reg)?;
    write_stages(out, reg)?;
    write_umbrella(out, reg)?;
    Ok(())
}

// ---------------------------------------------------------------- enums

fn write_enums(out: &Path) -> Result<()> {
    let body = format!(
        "{HEADER_NOTE}\
         #ifndef QUINTRA_GEN_ENUMS_H\n\
         #define QUINTRA_GEN_ENUMS_H\n\
         #include \"core/types.h\"\n\
         \n\
         /* FormTheme */\n\
         #define FORM_WOLFKIN  0\n\
         #define FORM_SAURAN   1\n\
         #define FORM_CORVIN   2\n\
         #define FORM_PICSEAN  3\n\
         #define FORM_VESPINE  4\n\
         \n\
         /* Rarity */\n\
         #define RARITY_COMMON   0\n\
         #define RARITY_UNCOMMON 1\n\
         #define RARITY_RARE     2\n\
         #define RARITY_BOSS     3\n\
         \n\
         /* ItemKind discriminants */\n\
         #define ITEM_KIND_WEAPON     0\n\
         #define ITEM_KIND_ACTIVE     1\n\
         #define ITEM_KIND_PASSIVE    2\n\
         #define ITEM_KIND_CONSUMABLE 3\n\
         \n\
         /* ProjectileKind */\n\
         #define PROJ_BULLET    0\n\
         #define PROJ_BOLT      1\n\
         #define PROJ_HOMING    2\n\
         #define PROJ_WAVE      3\n\
         #define PROJ_SPREAD3   4\n\
         #define PROJ_SPREAD5   5\n\
         #define PROJ_BOOMERANG 6\n\
         #define PROJ_BOMB      7\n\
         #define PROJ_LASER     8\n\
         #define PROJ_BUBBLE    9\n\
         #define PROJ_SPIKE     10\n\
         #define PROJ_SHURIKEN  11\n\
         \n\
         /* Status */\n\
         #define STATUS_NONE     0\n\
         #define STATUS_BURNING  1\n\
         #define STATUS_FROZEN   2\n\
         #define STATUS_POISONED 3\n\
         #define STATUS_STUNNED  4\n\
         #define STATUS_CURSED   5\n\
         #define STATUS_MARKED   6\n\
         \n\
         /* Stat */\n\
         #define STAT_HP  0\n\
         #define STAT_MP  1\n\
         #define STAT_ATK 2\n\
         #define STAT_DEF 3\n\
         #define STAT_SPD 4\n\
         #define STAT_LCK 5\n\
         \n\
         /* AiScript discriminants */\n\
         #define AI_WALKER     0\n\
         #define AI_CHASER     1\n\
         #define AI_CHARGER    2\n\
         #define AI_SHOOTER    3\n\
         #define AI_SPINNER    4\n\
         #define AI_TURRET     5\n\
         #define AI_REPLICATOR 9\n\
         #define AI_SPRAY      6\n\
         #define AI_AIMEDBURST 7\n\
         #define AI_TELEPORT   8\n\
         \n\
         /* RoomSize */\n\
         #define ROOM_SMALL  0\n\
         #define ROOM_MEDIUM 1\n\
         #define ROOM_LARGE  2\n\
         \n\
         /* RoomKind */\n\
         #define ROOMKIND_COMBAT   0\n\
         #define ROOMKIND_TREASURE 1\n\
         #define ROOMKIND_SHOP     2\n\
         #define ROOMKIND_ALTAR    3\n\
         #define ROOMKIND_PUZZLE   4\n\
         #define ROOMKIND_BOSS     5\n\
         \n\
         /* SpawnRole */\n\
         #define SPAWN_ENEMY      0\n\
         #define SPAWN_PICKUP     1\n\
         #define SPAWN_HAZARD     2\n\
         #define SPAWN_DECORATION 3\n\
         \n\
         /* Effect discriminants (3-byte payload encoding) */\n\
         #define EFFECT_STAT_BOOST      0\n\
         #define EFFECT_ON_HIT          1\n\
         #define EFFECT_ON_ROOM_CLEAR   2\n\
         #define EFFECT_ON_PICKUP       3\n\
         #define EFFECT_ON_DAMAGE_TAKEN 4\n\
         #define EFFECT_DASH            5\n\
         #define EFFECT_HEAL_HEARTS     6\n\
         #define EFFECT_GRANT_MP        7\n\
         #define EFFECT_REVEAL_MAP      8\n\
         \n\
         /* Trigger discriminants (3-byte payload encoding) */\n\
         #define TRIGGER_SPAWN_PROJECTILE 0\n\
         #define TRIGGER_DEAL_DAMAGE      1\n\
         #define TRIGGER_APPLY_STATUS     2\n\
         #define TRIGGER_GIVE_COINS       3\n\
         \n\
         /* Door bitmask */\n\
         #define DOOR_N 0x1\n\
         #define DOOR_E 0x2\n\
         #define DOOR_S 0x4\n\
         #define DOOR_W 0x8\n\
         \n\
         #endif\n",
    );
    write_if_changed(out.join("enums.h"), body)?;
    Ok(())
}

// ---------------------------------------------------------------- classes

fn write_classes(out: &Path, reg: &Registry) -> Result<()> {
    let mut header = String::from(HEADER_NOTE);
    header.push_str(
        "#ifndef QUINTRA_GEN_CLASSES_H\n\
         #define QUINTRA_GEN_CLASSES_H\n\
         #include \"core/types.h\"\n\
         #include \"enums.h\"\n\
         \n\
         typedef struct {\n\
         \x20\x20\x20\x20u8 hp_max;\n\
         \x20\x20\x20\x20u8 mp_max;\n\
         \x20\x20\x20\x20u8 atk;\n\
         \x20\x20\x20\x20u8 def;\n\
         \x20\x20\x20\x20u8 spd;\n\
         } base_stats_t;\n\
         \n\
         typedef struct {\n\
         \x20\x20\x20\x20u8           id;\n\
         \x20\x20\x20\x20const char*  name;\n\
         \x20\x20\x20\x20u8           form_theme;\n\
         \x20\x20\x20\x20u8           palette;\n\
         \x20\x20\x20\x20u8           sprite_set;\n\
         \x20\x20\x20\x20u16          starter_weapon;\n\
         \x20\x20\x20\x20u16          signature_active;\n\
         \x20\x20\x20\x20u8           passive_perk;\n\
         \x20\x20\x20\x20base_stats_t base_stats;\n\
         } class_def_t;\n\
         \n",
    );
    header.push_str(&format!("#define N_CLASSES {}\n", reg.n_classes()));
    header.push_str("extern const class_def_t classes[];\n#endif\n");
    write_if_changed(out.join("classes.h"), header)?;

    let mut body = String::from(HEADER_NOTE);
    body.push_str("#include \"classes.h\"\n\nconst class_def_t classes[] = {\n");
    for c in &reg.classes { body.push_str(&emit_class(c)); }
    body.push_str("};\n");
    write_if_changed(out.join("classes.c"), body)?;
    Ok(())
}

fn emit_class(c: &Class) -> String {
    format!(
        "    {{ .id={}, .name=\"{}\", .form_theme={}, .palette={}, .sprite_set={},\n\
        \x20     .starter_weapon={}, .signature_active={}, .passive_perk={},\n\
        \x20     .base_stats={{ {} }} }},\n",
        c.id.raw(), esc(c.name), form(c.form_theme), c.palette.raw(), c.sprite_set.raw(),
        c.starter_weapon.raw(), c.signature_active.raw(), c.passive_perk.raw(),
        emit_base_stats(c.base_stats),
    )
}

fn emit_base_stats(s: BaseStats) -> String {
    format!(".hp_max={}, .mp_max={}, .atk={}, .def={}, .spd={}",
        s.hp_max, s.mp_max, s.atk, s.def, s.spd)
}

// ---------------------------------------------------------------- items

fn write_items(out: &Path, reg: &Registry) -> Result<()> {
    let mut h = String::from(HEADER_NOTE);
    h.push_str(
        "#ifndef QUINTRA_GEN_ITEMS_H\n\
         #define QUINTRA_GEN_ITEMS_H\n\
         #include \"core/types.h\"\n\
         #include \"enums.h\"\n\
         \n\
         /* Effect: tagged record. kind = EFFECT_*; d0..d2 are kind-specific. */\n\
         typedef struct { u8 kind; u8 d0; u8 d1; u8 d2; } effect_t;\n\
         \n\
         typedef struct {\n\
         \x20\x20\x20\x20u16             id;\n\
         \x20\x20\x20\x20const char*     name;\n\
         \x20\x20\x20\x20const char*     description;\n\
         \x20\x20\x20\x20u8              kind;       /* ITEM_KIND_* */\n\
         \x20\x20\x20\x20u8              p0;         /* kind payload */\n\
         \x20\x20\x20\x20u8              p1;\n\
         \x20\x20\x20\x20u8              p2;\n\
         \x20\x20\x20\x20u8              p3;\n\
         \x20\x20\x20\x20u8              icon_sprite;\n\
         \x20\x20\x20\x20u8              palette;\n\
         \x20\x20\x20\x20u8              rarity;\n\
         \x20\x20\x20\x20u8              n_effects;\n\
         \x20\x20\x20\x20const effect_t* effects;\n\
         } item_def_t;\n\
         \n",
    );
    h.push_str(&format!("#define N_ITEMS {}\n", reg.n_items()));
    h.push_str("extern const item_def_t items[];\n#endif\n");
    write_if_changed(out.join("items.h"), h)?;

    let mut b = String::from(HEADER_NOTE);
    b.push_str("#include \"items.h\"\n\n");
    // Emit per-item effects arrays (or NULL when empty)
    for item in &reg.items {
        if item.effects.is_empty() { continue; }
        b.push_str(&format!("static const effect_t _eff_item_{}[] = {{\n", item.id.raw()));
        for e in item.effects { b.push_str(&format!("    {},\n", emit_effect(e))); }
        b.push_str("};\n\n");
    }
    b.push_str("const item_def_t items[] = {\n");
    for item in &reg.items { b.push_str(&emit_item(item)); }
    b.push_str("};\n");
    write_if_changed(out.join("items.c"), b)?;
    Ok(())
}

fn emit_item(i: &Item) -> String {
    let (kind_tag, p0, p1, p2, p3) = match i.kind {
        ItemKind::Weapon { fire_rate, damage, projectile, mp_cost } =>
            ("ITEM_KIND_WEAPON", fire_rate, damage, proj_kind(projectile), mp_cost),
        ItemKind::Active { cooldown_rooms } =>
            ("ITEM_KIND_ACTIVE", cooldown_rooms, 0, 0, 0),
        ItemKind::Passive =>
            ("ITEM_KIND_PASSIVE", 0, 0, 0, 0),
        ItemKind::Consumable { uses } =>
            ("ITEM_KIND_CONSUMABLE", uses, 0, 0, 0),
    };
    let (n_eff, eff_ptr) = if i.effects.is_empty() {
        (0_usize, "(const effect_t*)0".to_string())
    } else {
        (i.effects.len(), format!("_eff_item_{}", i.id.raw()))
    };
    format!(
        "    {{ .id={}, .name=\"{}\", .description=\"{}\",\n\
        \x20     .kind={}, .p0={}, .p1={}, .p2={}, .p3={},\n\
        \x20     .icon_sprite={}, .palette={}, .rarity={},\n\
        \x20     .n_effects={}, .effects={} }},\n",
        i.id.raw(), esc(i.name), esc(i.description),
        kind_tag, p0, p1, p2, p3,
        i.icon_sprite.raw(), i.palette.raw(), rarity(i.rarity),
        n_eff, eff_ptr,
    )
}

fn emit_effect(e: &Effect) -> String {
    let (k, d0, d1, d2) = match *e {
        Effect::StatBoost { stat, delta } =>
            ("EFFECT_STAT_BOOST", stat_disc(stat), delta as u8, 0),
        Effect::OnHit(t)             => ("EFFECT_ON_HIT",          trig_disc(t), trig_d0(t), trig_d1(t)),
        Effect::OnRoomClear(t)       => ("EFFECT_ON_ROOM_CLEAR",   trig_disc(t), trig_d0(t), trig_d1(t)),
        Effect::OnPickup(t)          => ("EFFECT_ON_PICKUP",       trig_disc(t), trig_d0(t), trig_d1(t)),
        Effect::OnDamageTaken(t)     => ("EFFECT_ON_DAMAGE_TAKEN", trig_disc(t), trig_d0(t), trig_d1(t)),
        Effect::Dash { iframes, dist } => ("EFFECT_DASH", iframes, dist, 0),
        Effect::HealHearts(n)        => ("EFFECT_HEAL_HEARTS", n, 0, 0),
        Effect::GrantMp(n)           => ("EFFECT_GRANT_MP", n, 0, 0),
        Effect::RevealMap            => ("EFFECT_REVEAL_MAP", 0, 0, 0),
    };
    format!("{{ .kind={}, .d0={}, .d1={}, .d2={} }}", k, d0, d1, d2)
}

fn trig_disc(t: Trigger) -> u8 {
    match t {
        Trigger::SpawnProjectile { .. } => 0,
        Trigger::DealDamage     { .. }  => 1,
        Trigger::ApplyStatus    { .. }  => 2,
        Trigger::GiveCoins(_)           => 3,
    }
}
fn trig_d0(t: Trigger) -> u8 {
    match t {
        Trigger::SpawnProjectile { kind, .. } => proj_kind(kind),
        Trigger::DealDamage     { amount, .. } => amount,
        Trigger::ApplyStatus    { status, .. } => status_disc(status),
        Trigger::GiveCoins(n)                  => n,
    }
}
fn trig_d1(t: Trigger) -> u8 {
    match t {
        Trigger::SpawnProjectile { count, .. } => count,
        Trigger::DealDamage     { radius, .. } => radius,
        Trigger::ApplyStatus    { duration_ticks, .. } => duration_ticks,
        Trigger::GiveCoins(_) => 0,
    }
}

// ---------------------------------------------------------------- enemies

fn write_enemies(out: &Path, reg: &Registry) -> Result<()> {
    let mut h = String::from(HEADER_NOTE);
    h.push_str(
        "#ifndef QUINTRA_GEN_ENEMIES_H\n\
         #define QUINTRA_GEN_ENEMIES_H\n\
         #include \"core/types.h\"\n\
         #include \"enums.h\"\n\
         \n\
         typedef struct {\n\
         \x20\x20\x20\x20u8 hp;\n\
         \x20\x20\x20\x20u8 damage;\n\
         \x20\x20\x20\x20u8 speed;\n\
         \x20\x20\x20\x20u8 score;\n\
         \x20\x20\x20\x20u8 weakness;\n\
         \x20\x20\x20\x20u8 poise;\n\
         } enemy_stats_t;\n\
         \n\
         typedef struct {\n\
         \x20\x20\x20\x20u8            id;\n\
         \x20\x20\x20\x20const char*   name;\n\
         \x20\x20\x20\x20u8            sprite_set;\n\
         \x20\x20\x20\x20u8            palette;\n\
         \x20\x20\x20\x20enemy_stats_t stats;\n\
         \x20\x20\x20\x20u8            ai_kind;     /* AI_* */\n\
         \x20\x20\x20\x20u8            ai_p0;\n\
         \x20\x20\x20\x20u8            ai_p1;\n\
         \x20\x20\x20\x20u8            ai_p2;\n\
         \x20\x20\x20\x20u8            drop_table;\n\
         \x20\x20\x20\x20u8            n_biomes;\n\
         \x20\x20\x20\x20const u8*     biomes;\n\
         } enemy_def_t;\n\
         \n",
    );
    h.push_str(&format!("#define N_ENEMIES {}\n", reg.n_enemies()));
    h.push_str("extern const enemy_def_t enemies[];\n#endif\n");
    write_if_changed(out.join("enemies.h"), h)?;

    let mut b = String::from(HEADER_NOTE);
    b.push_str("#include \"enemies.h\"\n\n");
    for e in &reg.enemies {
        b.push_str(&format!("static const u8 _bio_enemy_{}[] = {{", e.id.raw()));
        for bi in e.biomes { b.push_str(&format!(" {},", bi.raw())); }
        b.push_str(" };\n");
    }
    b.push('\n');
    b.push_str("const enemy_def_t enemies[] = {\n");
    for e in &reg.enemies { b.push_str(&emit_enemy(e)); }
    b.push_str("};\n");
    write_if_changed(out.join("enemies.c"), b)?;
    Ok(())
}

fn emit_enemy(e: &Enemy) -> String {
    let (ak, p0, p1, p2) = match e.ai_script {
        AiScriptId::Walker  => ("AI_WALKER", 0, 0, 0),
        AiScriptId::Chaser  => ("AI_CHASER", 0, 0, 0),
        AiScriptId::Charger { telegraph_ticks, charge_speed } =>
            ("AI_CHARGER", telegraph_ticks, charge_speed, 0),
        AiScriptId::Shooter { fire_rate, projectile, pattern } => {
            let (pat_d, pat_n) = shot_pattern(pattern);
            ("AI_SHOOTER", fire_rate, proj_kind(projectile), pat_d | (pat_n << 4))
        },
        AiScriptId::Spinner { radius, fire_rate } =>
            ("AI_SPINNER", radius, fire_rate, 0),
        AiScriptId::Turret { rotation, fire_rate } =>
            ("AI_TURRET", rotation, fire_rate, 0),
        AiScriptId::SprayPattern { angles, fire_rate } =>
            ("AI_SPRAY", angles, fire_rate, 0),
        AiScriptId::AimedBurst { burst_size, recovery_ticks } =>
            ("AI_AIMEDBURST", burst_size, recovery_ticks, 0),
        AiScriptId::Teleporter { blink_rate, appear_dist } =>
            ("AI_TELEPORT", blink_rate, appear_dist, 0),
        AiScriptId::Replicator { open_ticks, closed_ticks } =>
            ("AI_REPLICATOR", open_ticks, closed_ticks, 0),
    };
    format!(
        "    {{ .id={}, .name=\"{}\", .sprite_set={}, .palette={},\n\
        \x20     .stats={{ {} }},\n\
        \x20     .ai_kind={}, .ai_p0={}, .ai_p1={}, .ai_p2={},\n\
        \x20     .drop_table={}, .n_biomes={}, .biomes=_bio_enemy_{} }},\n",
        e.id.raw(), esc(e.name), e.sprite_set.raw(), e.palette.raw(),
        emit_enemy_stats(e.stats),
        ak, p0, p1, p2,
        e.drop_table.raw(), e.biomes.len(), e.id.raw(),
    )
}

fn emit_enemy_stats(s: EnemyStats) -> String {
    format!(".hp={}, .damage={}, .speed={}, .score={}, .weakness={}, .poise={}",
        s.hp, s.damage, s.speed, s.score, s.weakness, s.poise)
}

fn shot_pattern(p: ShotPattern) -> (u8, u8) {
    match p {
        ShotPattern::Single        => (0, 0),
        ShotPattern::Fan(n)        => (1, n),
        ShotPattern::Ring(n)       => (2, n),
        ShotPattern::Burst(n)      => (3, n),
        ShotPattern::Spiral { steps } => (4, steps),
    }
}

// ---------------------------------------------------------------- biomes

fn write_biomes(out: &Path, reg: &Registry) -> Result<()> {
    let mut h = String::from(HEADER_NOTE);
    h.push_str(
        "#ifndef QUINTRA_GEN_BIOMES_H\n\
         #define QUINTRA_GEN_BIOMES_H\n\
         #include \"core/types.h\"\n\
         #include \"enums.h\"\n\
         \n\
         typedef struct { u8 enemy_id; u8 weight; } enemy_pool_entry_t;\n\
         \n\
         typedef struct {\n\
         \x20\x20\x20\x20u8           id;\n\
         \x20\x20\x20\x20const char*  name;\n\
         \x20\x20\x20\x20u8           depth_min;\n\
         \x20\x20\x20\x20u8           depth_max;\n\
         \x20\x20\x20\x20u8           tileset;\n\
         \x20\x20\x20\x20u8           bg_pal[4];\n\
         \x20\x20\x20\x20u8           music_track;\n\
         \x20\x20\x20\x20u8           n_enemy_pool;\n\
         \x20\x20\x20\x20const enemy_pool_entry_t* enemy_pool;\n\
         \x20\x20\x20\x20u8           n_rooms_pool;\n\
         \x20\x20\x20\x20const u16*   room_pool;\n\
         \x20\x20\x20\x20u8           min_rooms;\n\
         \x20\x20\x20\x20u8           max_rooms;\n\
         \x20\x20\x20\x20u8           has_shop;\n\
         \x20\x20\x20\x20u8           has_altar;\n\
         \x20\x20\x20\x20u8           boss;\n\
         } biome_def_t;\n\
         \n",
    );
    h.push_str(&format!("#define N_BIOMES {}\n", reg.n_biomes()));
    h.push_str("extern const biome_def_t biomes[];\n#endif\n");
    write_if_changed(out.join("biomes.h"), h)?;

    let mut b = String::from(HEADER_NOTE);
    b.push_str("#include \"biomes.h\"\n\n");
    for bi in &reg.biomes {
        b.push_str(&format!("static const enemy_pool_entry_t _epool_biome_{}[] = {{\n", bi.id.raw()));
        for (eid, w) in bi.enemy_pool {
            b.push_str(&format!("    {{ {}, {} }},\n", eid.raw(), w));
        }
        b.push_str("};\n");

        b.push_str(&format!("static const u16 _rpool_biome_{}[] = {{", bi.id.raw()));
        for tid in bi.room_template_pool {
            b.push_str(&format!(" {},", tid.raw()));
        }
        b.push_str(" };\n\n");
    }

    b.push_str("const biome_def_t biomes[] = {\n");
    for bi in &reg.biomes { b.push_str(&emit_biome(bi)); }
    b.push_str("};\n");
    write_if_changed(out.join("biomes.c"), b)?;
    Ok(())
}

fn emit_biome(b: &quintra_content::Biome) -> String {
    format!(
        "    {{ .id={}, .name=\"{}\", .depth_min={}, .depth_max={},\n\
        \x20     .tileset={}, .bg_pal={{ {},{},{},{} }}, .music_track={},\n\
        \x20     .n_enemy_pool={}, .enemy_pool=_epool_biome_{},\n\
        \x20     .n_rooms_pool={}, .room_pool=_rpool_biome_{},\n\
        \x20     .min_rooms={}, .max_rooms={},\n\
        \x20     .has_shop={}, .has_altar={}, .boss={} }},\n",
        b.id.raw(), esc(b.name), b.depth_range.0, b.depth_range.1,
        b.tileset.raw(),
        b.bg_palettes[0].raw(), b.bg_palettes[1].raw(),
        b.bg_palettes[2].raw(), b.bg_palettes[3].raw(),
        b.music_track.raw(),
        b.enemy_pool.len(), b.id.raw(),
        b.room_template_pool.len(), b.id.raw(),
        b.min_rooms, b.max_rooms,
        b.has_shop as u8, b.has_altar as u8, b.boss.raw(),
    )
}

// ---------------------------------------------------------------- rooms

fn write_rooms(out: &Path, reg: &Registry) -> Result<()> {
    let mut h = String::from(HEADER_NOTE);
    h.push_str(
        "#ifndef QUINTRA_GEN_ROOMS_H\n\
         #define QUINTRA_GEN_ROOMS_H\n\
         #include \"core/types.h\"\n\
         #include \"enums.h\"\n\
         \n\
         typedef struct { u8 x; u8 y; u8 role; } spawn_slot_t;\n\
         \n\
         typedef struct {\n\
         \x20\x20\x20\x20u16          id;\n\
         \x20\x20\x20\x20u8           size;       /* ROOM_* */\n\
         \x20\x20\x20\x20u16          layout;     /* tilemap blob id */\n\
         \x20\x20\x20\x20u8           doors;      /* DOOR_* bitmask */\n\
         \x20\x20\x20\x20u8           kind;       /* ROOMKIND_* */\n\
         \x20\x20\x20\x20u8           n_slots;\n\
         \x20\x20\x20\x20const spawn_slot_t* slots;\n\
         } room_tpl_t;\n\
         \n",
    );
    h.push_str(&format!("#define N_ROOM_TEMPLATES {}\n", reg.n_room_templates()));
    h.push_str("extern const room_tpl_t room_templates[];\n#endif\n");
    write_if_changed(out.join("rooms.h"), h)?;

    let mut b = String::from(HEADER_NOTE);
    b.push_str("#include \"rooms.h\"\n\n");
    for r in &reg.room_templates {
        if r.spawn_slots.is_empty() { continue; }
        b.push_str(&format!("static const spawn_slot_t _slots_room_{}[] = {{\n", r.id.raw()));
        for s in r.spawn_slots {
            b.push_str(&format!("    {{ {}, {}, {} }},\n", s.x, s.y, spawn_role(s.role)));
        }
        b.push_str("};\n\n");
    }
    b.push_str("const room_tpl_t room_templates[] = {\n");
    for r in &reg.room_templates { b.push_str(&emit_room(r)); }
    b.push_str("};\n");
    write_if_changed(out.join("rooms.c"), b)?;
    Ok(())
}

fn emit_room(r: &RoomTemplate) -> String {
    let (n, slots) = if r.spawn_slots.is_empty() {
        (0_usize, "(const spawn_slot_t*)0".to_string())
    } else {
        (r.spawn_slots.len(), format!("_slots_room_{}", r.id.raw()))
    };
    format!(
        "    {{ .id={}, .size={}, .layout={}, .doors={}, .kind={}, .n_slots={}, .slots={} }},\n",
        r.id.raw(),
        match r.size {
            RoomSize::Small  => "ROOM_SMALL",
            RoomSize::Medium => "ROOM_MEDIUM",
            RoomSize::Large  => "ROOM_LARGE",
        },
        r.layout.raw(),
        r.doors.raw(),
        match r.kind {
            RoomKind::Combat   => "ROOMKIND_COMBAT",
            RoomKind::Treasure => "ROOMKIND_TREASURE",
            RoomKind::Shop     => "ROOMKIND_SHOP",
            RoomKind::Altar    => "ROOMKIND_ALTAR",
            RoomKind::Puzzle   => "ROOMKIND_PUZZLE",
            RoomKind::Boss     => "ROOMKIND_BOSS",
        },
        n, slots,
    )
}

// ---------------------------------------------------------------- zelda overworld

fn write_zelda_overworld(out: &Path, reg: &Registry) -> Result<()> {
    let mut h = String::from(HEADER_NOTE);
    h.push_str(
        "#ifndef QUINTRA_GEN_ZELDA_OVERWORLD_H\n\
         #define QUINTRA_GEN_ZELDA_OVERWORLD_H\n\
         #include \"core/types.h\"\n\
         #include \"enums.h\"\n\
         \n\
         #define ZELDA_CELL_OVERWORLD       0\n\
         #define ZELDA_CELL_CAVE_ENTRANCE   1\n\
         #define ZELDA_CELL_DUNGEON_ENTRANCE 2\n\
         #define ZELDA_CELL_VAULT           3\n\
         #define ZELDA_CELL_BOSS            4\n\
         \n\
         typedef struct {\n\
         \x20\x20\x20\x20u8 kind;\n\
         \x20\x20\x20\x20u8 edges;\n\
         \x20\x20\x20\x20u16 room_tpl;\n\
         \x20\x20\x20\x20screen_id_t secret;\n\
         \x20\x20\x20\x20screen_id_t stairs;\n\
         } zelda_screen_t;\n\
         \n\
         typedef struct {\n\
         \x20\x20\x20\x20biome_id_t id;\n\
         \x20\x20\x20\x20const char* name;\n\
         \x20\x20\x20\x20const zelda_screen_t* screen_grid;\n\
         } zelda_overworld_def_t;\n\
         \n",
    );
    h.push_str(&format!("#define N_ZELDA_OVERWORLDS {}\n", reg.n_zelda_overworlds()));
    h.push_str("extern const zelda_overworld_def_t zelda_overworlds[];\n#endif\n");
    write_if_changed(out.join("zelda_overworld.h"), h)?;

    let mut c = String::from(HEADER_NOTE);
    c.push_str("#include \"zelda_overworld.h\"\n\n");
    for z in &reg.zelda_overworlds {
        c.push_str(&format!("static const zelda_screen_t _zelda_grid_{}[16] = {{\n", z.id.raw()));
        for idx in 0..16 {
            c.push_str(&format!("    {},\n", emit_zelda_screen(z, idx)));
        }
        c.push_str("};\n\n");
    }
    c.push_str("const zelda_overworld_def_t zelda_overworlds[] = {\n");
    for z in &reg.zelda_overworlds {
        c.push_str(&format!(
            "    {{ .id={}, .name=\"{}\", .screen_grid=_zelda_grid_{} }},\n",
            z.id.raw(),
            esc(z.name),
            z.id.raw(),
        ));
    }
    c.push_str("};\n");
    write_if_changed(out.join("zelda_overworld.c"), c)?;
    Ok(())
}

fn emit_zelda_screen(z: &ZeldaOverworldBiome, idx: usize) -> String {
    let cell = z.cell(idx);
    format!(
        "{{ .kind={}, .edges={}, .room_tpl={}, .secret={}, .stairs={} }}",
        zelda_cell_kind(cell.cell_kind),
        cell.edges.raw(),
        cell.room_tpl_id.raw(),
        opt_screen_id(cell.secret_to),
        opt_screen_id(cell.staircase_to),
    )
}

// ---------------------------------------------------------------- umbrella

fn write_umbrella(out: &Path, _reg: &Registry) -> Result<()> {
    let body = format!(
        "{HEADER_NOTE}\
         #ifndef QUINTRA_GEN_CONTENT_H\n\
         #define QUINTRA_GEN_CONTENT_H\n\
         #include \"enums.h\"\n\
         #include \"classes.h\"\n\
         #include \"items.h\"\n\
         #include \"enemies.h\"\n\
         #include \"biomes.h\"\n\
         #include \"zelda_overworld.h\"\n\
         #include \"rooms.h\"\n\
         #include \"stages.h\"\n\
         #endif\n",
    );
    write_if_changed(out.join("content.h"), body).context("write content.h")?;
    Ok(())
}


// ---------------------------------------------------------------- stages

fn emit_pal4(p: &[quintra_content::Rgb5; 4]) -> String {
    format!("{{ 0x{:04X}, 0x{:04X}, 0x{:04X}, 0x{:04X} }}",
        p[0].to_bgr555(), p[1].to_bgr555(), p[2].to_bgr555(), p[3].to_bgr555())
}

fn write_stages(out: &Path, reg: &Registry) -> Result<()> {
    let n = reg.stages.len();

    let h = format!(
        "{HEADER_NOTE}\
         #ifndef QUINTRA_GEN_STAGES_H\n\
         #define QUINTRA_GEN_STAGES_H\n\
         #include \"core/types.h\"\n\
         \n\
         #define N_STAGES {n}\n\
         \n\
         /* [stage][floor|wall|crystal|door][color 0-3], BGR555 */\n\
         extern const u16 stage_pal[N_STAGES][4][4];\n\
         /* Large-boss OBJ tint per stage: [_, rim, body-dark, glow] */\n\
         extern const u16 boss_stage_pal[N_STAGES][4];\n\
         /* Cracked-wall palette — constant across stages */\n\
         extern const u16 stage_pal_crack[4];\n\
         /* Display names (PACK screen) */\n\
         extern const char *const stage_names[N_STAGES];\n\
         /* Large-boss stat bonuses per stage (indexed by CLAMPED stage) */\n\
         extern const u8 stage_boss_hp[N_STAGES];\n\
         extern const u8 stage_boss_dmg[N_STAGES];\n\
         /* Mini-boss silhouette per stage: 0 Sentinel, 1 Orc, 2 Skeleton.\n\
            Single source for BOTH the art loader and the palette pick. */\n\
         extern const u8 stage_mb_variant[N_STAGES];\n\
         /* Weighted normal-room rosters per stage (ids + weights,\n\
            stage_pool_n entries each; weights sum <= 255) */\n\
         #define STAGE_POOL_MAX 4\n\
         extern const u8 stage_pool_ids[N_STAGES][STAGE_POOL_MAX];\n\
         extern const u8 stage_pool_w[N_STAGES][STAGE_POOL_MAX];\n\
         extern const u8 stage_pool_n[N_STAGES];\n\
         extern const u8 stage_pool_total[N_STAGES];\n\
         #endif\n");
    write_if_changed(out.join("stages.h"), h).context("write stages.h")?;

    let mut c = String::from(HEADER_NOTE);
    c.push_str("#include \"stages.h\"\n\n");

    c.push_str(&format!("const u16 stage_pal[N_STAGES][4][4] = {{\n"));
    for s in &reg.stages {
        c.push_str(&format!("    /* {} — {} */\n    {{\n", s.id, esc(s.name)));
        for pal in [&s.floor, &s.wall, &s.crystal, &s.door] {
            c.push_str(&format!("        {},\n", emit_pal4(pal)));
        }
        c.push_str("    },\n");
    }
    c.push_str("};\n\n");

    c.push_str("const u16 boss_stage_pal[N_STAGES][4] = {\n");
    for s in &reg.stages {
        c.push_str(&format!("    {},   /* {} */\n", emit_pal4(&s.boss), esc(s.name)));
    }
    c.push_str("};\n\n");

    let crack = quintra_game_content::stages::CRACK_PAL;
    c.push_str(&format!("const u16 stage_pal_crack[4] = {};\n\n", emit_pal4(&crack)));

    c.push_str("const char *const stage_names[N_STAGES] = {\n");
    for s in &reg.stages {
        c.push_str(&format!("    \"{}\",\n", esc(s.name)));
    }
    c.push_str("};\n\n");

    let list = |f: &dyn Fn(&quintra_content::StageTheme) -> u8| {
        reg.stages.iter().map(|s| f(s).to_string()).collect::<Vec<_>>().join(", ")
    };
    c.push_str(&format!("const u8 stage_boss_hp[N_STAGES] = {{ {} }};\n",
        list(&|s| s.boss_hp_bonus)));
    c.push_str(&format!("const u8 stage_boss_dmg[N_STAGES] = {{ {} }};\n",
        list(&|s| s.boss_dmg_bonus)));
    c.push_str(&format!("const u8 stage_mb_variant[N_STAGES] = {{ {} }};\n",
        list(&|s| s.mb_variant)));

    c.push_str("\nconst u8 stage_pool_ids[N_STAGES][STAGE_POOL_MAX] = {\n");
    for s in &reg.stages {
        let mut ids = [0u8; 4];
        for (i, &(eid, _)) in s.enemy_pool.iter().enumerate() { ids[i] = eid; }
        c.push_str(&format!("    {{ {}, {}, {}, {} }},\n", ids[0], ids[1], ids[2], ids[3]));
    }
    c.push_str("};\n");
    c.push_str("const u8 stage_pool_w[N_STAGES][STAGE_POOL_MAX] = {\n");
    for s in &reg.stages {
        let mut ws = [0u8; 4];
        for (i, &(_, w)) in s.enemy_pool.iter().enumerate() { ws[i] = w; }
        c.push_str(&format!("    {{ {}, {}, {}, {} }},\n", ws[0], ws[1], ws[2], ws[3]));
    }
    c.push_str("};\n");
    c.push_str(&format!("const u8 stage_pool_n[N_STAGES] = {{ {} }};\n",
        list(&|s| s.enemy_pool.len() as u8)));
    c.push_str(&format!("const u8 stage_pool_total[N_STAGES] = {{ {} }};\n",
        list(&|s| s.enemy_pool.iter().map(|&(_, w)| w).sum::<u8>())));

    write_if_changed(out.join("stages.c"), c).context("write stages.c")?;
    let _ = n;
    Ok(())
}

// ---------------------------------------------------------------- helpers

/// Replace a generated file only when its bytes changed. Besides avoiding
/// needless disk churn, preserving the mtime is part of the build contract:
/// all cartridge objects conservatively depend on all generated headers.
fn write_if_changed(path: PathBuf, contents: impl AsRef<[u8]>) -> Result<bool> {
    let contents = contents.as_ref();
    if fs::read(&path).map(|current| current == contents).unwrap_or(false) {
        return Ok(false);
    }
    fs::write(&path, contents).with_context(|| format!("write {}", path.display()))?;
    Ok(true)
}

fn esc(s: &str) -> String {
    s.chars().flat_map(|c| match c {
        '"' => "\\\"".chars().collect::<Vec<_>>(),
        '\\' => "\\\\".chars().collect(),
        '\n' => "\\n".chars().collect(),
        c if (c as u32) < 0x20 => format!("\\x{:02x}", c as u32).chars().collect(),
        c => vec![c],
    }).collect()
}

fn form(f: FormTheme) -> &'static str {
    match f {
        FormTheme::Wolfkin => "FORM_WOLFKIN",
        FormTheme::Sauran  => "FORM_SAURAN",
        FormTheme::Corvin  => "FORM_CORVIN",
        FormTheme::Picsean => "FORM_PICSEAN",
        FormTheme::Vespine => "FORM_VESPINE",
    }
}

fn rarity(r: Rarity) -> &'static str {
    match r {
        Rarity::Common   => "RARITY_COMMON",
        Rarity::Uncommon => "RARITY_UNCOMMON",
        Rarity::Rare     => "RARITY_RARE",
        Rarity::Boss     => "RARITY_BOSS",
    }
}

fn proj_kind(p: ProjectileKind) -> u8 {
    match p {
        ProjectileKind::Bullet    => 0,
        ProjectileKind::Bolt      => 1,
        ProjectileKind::Homing    => 2,
        ProjectileKind::Wave      => 3,
        ProjectileKind::Spread3   => 4,
        ProjectileKind::Spread5   => 5,
        ProjectileKind::Boomerang => 6,
        ProjectileKind::Bomb      => 7,
        ProjectileKind::Laser     => 8,
        ProjectileKind::Bubble    => 9,
        ProjectileKind::Spike     => 10,
        ProjectileKind::Shuriken  => 11,
    }
}

fn status_disc(s: Status) -> u8 {
    match s {
        Status::None     => 0,
        Status::Burning  => 1,
        Status::Frozen   => 2,
        Status::Poisoned => 3,
        Status::Stunned  => 4,
        Status::Cursed   => 5,
        Status::Marked   => 6,
    }
}

fn zelda_cell_kind(kind: ScreenCellKind) -> &'static str {
    match kind {
        ScreenCellKind::Overworld => "ZELDA_CELL_OVERWORLD",
        ScreenCellKind::CaveEntrance => "ZELDA_CELL_CAVE_ENTRANCE",
        ScreenCellKind::DungeonEntrance => "ZELDA_CELL_DUNGEON_ENTRANCE",
        ScreenCellKind::Vault => "ZELDA_CELL_VAULT",
        ScreenCellKind::Boss => "ZELDA_CELL_BOSS",
    }
}

fn opt_screen_id(id: Option<u8>) -> String {
    match id {
        Some(id) => id.to_string(),
        None => "ID_NONE_U8".to_string(),
    }
}

fn stat_disc(s: Stat) -> u8 {
    match s {
        Stat::Hp  => 0,
        Stat::Mp  => 1,
        Stat::Atk => 2,
        Stat::Def => 3,
        Stat::Spd => 4,
        Stat::Lck => 5,
    }
}

fn spawn_role(r: SpawnRole) -> &'static str {
    match r {
        SpawnRole::Enemy      => "SPAWN_ENEMY",
        SpawnRole::Pickup     => "SPAWN_PICKUP",
        SpawnRole::Hazard     => "SPAWN_HAZARD",
        SpawnRole::Decoration => "SPAWN_DECORATION",
    }
}

#[allow(dead_code)]
fn door_mask(d: DoorMask) -> u8 { d.raw() }

#[allow(dead_code)]
fn spawn_slot(s: SpawnSlot) -> String {
    format!("{}, {}, {}", s.x, s.y, spawn_role(s.role))
}

#[cfg(test)]
mod tests {
    use super::write_if_changed;
    use std::fs;

    #[test]
    fn unchanged_output_is_not_rewritten() {
        let path = std::env::temp_dir().join(format!(
            "quintra-codegen-idempotent-{}-{}",
            std::process::id(),
            std::thread::current().name().unwrap_or("test")
        ));
        let _ = fs::remove_file(&path);
        assert!(write_if_changed(path.clone(), b"first").unwrap());
        assert!(!write_if_changed(path.clone(), b"first").unwrap());
        assert!(write_if_changed(path.clone(), b"second").unwrap());
        assert_eq!(fs::read(&path).unwrap(), b"second");
        let _ = fs::remove_file(path);
    }
}
