// Auto-generated by quintra-assets (tools/crates/quintra-assets) — do not edit by hand.
#ifndef QUINTRA_RENDER_SPRITES_GEN_H
#define QUINTRA_RENDER_SPRITES_GEN_H

#include "core/types.h"

// 16x16 player class metasprites
extern const u8 sprite_class_wolfkin[64];
extern const u8 sprite_class_sauran[64];
extern const u8 sprite_class_corvin[64];
extern const u8 sprite_class_picsean[64];
extern const u8 sprite_class_vespine[64];
extern const u8 sprite_class_wolfkin_walk[64];
extern const u8 sprite_class_sauran_walk[64];
extern const u8 sprite_class_corvin_walk[64];
extern const u8 sprite_class_picsean_walk[64];
extern const u8 sprite_class_vespine_walk[64];
extern const u8 sprite_class_wolfkin_ascended[64];
extern const u8 sprite_class_sauran_ascended[64];
extern const u8 sprite_class_corvin_ascended[64];
extern const u8 sprite_class_picsean_ascended[64];
extern const u8 sprite_class_vespine_ascended[64];

// 8x8 enemy sprites
extern const u8 sprite_enemy_crawler[16];
extern const u8 sprite_enemy_hornet[16];
extern const u8 sprite_enemy_skeleton[16];
extern const u8 sprite_enemy_orc[16];
extern const u8 sprite_enemy_bomber[16];
extern const u8 sprite_enemy_shade[16];
extern const u8 sprite_enemy_warlock[16];
extern const u8 sprite_enemy_rope[16];
extern const u8 sprite_enemy_sentry[16];
extern const u8 sprite_enemy_fold_star[16];
extern const u8 sprite_enemy_flutterbat[16];
extern const u8 sprite_enemy_gloam_leech[16];
extern const u8 sprite_enemy_cinder_maw[16];
extern const u8 sprite_enemy_rift_ooze[16];
extern const u8 sprite_enemy_mirror_moth[16];
extern const u8 sprite_enemy_mire_spore[16];
extern const u8 sprite_enemy_echo_guard[16];
extern const u8 sprite_enemy_rune_lantern[16];

// 8x8 effects and village roles
extern const u8 sprite_fx_bullet_a[16];
extern const u8 sprite_fx_bullet_b[16];
extern const u8 sprite_fx_muzzle[16];
extern const u8 sprite_fx_impact[16];
extern const u8 sprite_fx_wisp[16];
extern const u8 sprite_fx_item_orb[16];
extern const u8 sprite_fx_shop_tag[16];
extern const u8 sprite_fx_merchant_callout[16];
extern const u8 sprite_fx_surge_orb[16];
extern const u8 sprite_fx_shield_aura[16];
extern const u8 sprite_fx_villager[16];
extern const u8 sprite_fx_merchant[16];
extern const u8 sprite_fx_smith[16];
extern const u8 sprite_fx_apothecary[16];

// 8x8 dungeon background tiles
extern const u8 bgt_floor_plain[16];
extern const u8 bgt_floor_crack[16];
extern const u8 bgt_floor_pebble[16];
extern const u8 bgt_wall_brick[16];
extern const u8 bgt_door_frame[16];
extern const u8 bgt_pillar[16];
extern const u8 bgt_crystal[16];
extern const u8 bgt_rubble[16];
extern const u8 bgt_wall_crack[16];
extern const u8 bgt_block[16];
extern const u8 bgt_spikes[16];
extern const u8 bgt_pot[16];
extern const u8 bgt_switch[16];
extern const u8 bgt_portal[16];
extern const u8 bgt_block16_tl[16];
extern const u8 bgt_block16_tr[16];
extern const u8 bgt_block16_bl[16];
extern const u8 bgt_block16_br[16];

// 16x16 mini-boss and bruiser metasprites
extern const u8 sprite_boss_sentinel[64];
extern const u8 sprite_miniboss_orc[64];
extern const u8 sprite_miniboss_skeleton[64];
extern const u8 sprite_bruiser_orc[64];
extern const u8 sprite_bruiser_bomber[64];
extern const u8 sprite_bruiser_warlock[64];

// Nine 32x32 stage bosses (9 * 16 tiles * 16 bytes)
extern const u8 sprite_boss_stages[2304];

#endif
