//! quintra-assets — sprite/tile authoring pipeline.
//!
//! The ASCII grids in grids.rs and the parametric bosses in bosses.rs are
//! the pixel source of truth; this binary compiles them to GBDK 2bpp C
//! arrays (src/render/sprites_gen.c). Ported from the retired
//! scripts/sprite_authoring.py — output is pinned byte-identical by the
//! golden test below.

use std::fmt::Write as _;
use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::Parser;

mod bosses;
mod gbc;
mod grids;

use gbc::{emit_metasprite_c_array, emit_tile_c_array, parse_grid, scale2x,
          sprite_to_tiles, tile_2bpp_bytes};

#[derive(Parser, Debug)]
#[command(name = "quintra-assets")]
struct Args {
    /// Output C file (use '-' for stdout)
    #[arg(long, default_value = "src/render/sprites_gen.c")]
    out: PathBuf,
}

pub fn generate() -> String {
    let mut o = String::new();

    let _ = writeln!(o, "// Auto-generated by quintra-assets (tools/crates/quintra-assets) — do not edit by hand.");
    let _ = writeln!(o, "// Glyph map: .=0 transparent, 1=light, 2=mid, 3=dark");
    let _ = writeln!(o);
    let _ = writeln!(o, "#pragma bank 2");
    let _ = writeln!(o);
    let _ = writeln!(o, "#include \"core/types.h\"");
    let _ = writeln!(o);

    // Players (16x16 = 4 tiles each; walk cycle is OAM flips at render time)
    for (name, lines) in grids::PLAYERS {
        let grid = parse_grid(lines);
        let tiles = sprite_to_tiles(&grid, grids::PLAYER_W, grids::PLAYER_H);
        let _ = writeln!(o, "{}", emit_metasprite_c_array(
            &format!("sprite_class_{name}"), &tiles));
    }

    // Enemies (8x8 = 1 tile; waddle is an OAM X-flip)
    for (name, lines) in grids::ENEMIES_8 {
        let grid = parse_grid(lines);
        let _ = writeln!(o, "{}", emit_tile_c_array(
            &format!("sprite_enemy_{name}"), &tile_2bpp_bytes(&grid)));
    }

    // FX sprites (8x8)
    for (name, lines) in grids::FX_8 {
        let grid = parse_grid(lines);
        let _ = writeln!(o, "{}", emit_tile_c_array(
            &format!("sprite_fx_{name}"), &tile_2bpp_bytes(&grid)));
    }

    // Dungeon BG tiles (8x8)
    for (name, lines) in grids::DUNGEON_TILES {
        let grid = parse_grid(lines);
        let _ = writeln!(o, "{}", emit_tile_c_array(
            &format!("bgt_{name}"), &tile_2bpp_bytes(&grid)));
    }

    // Pushable block: a 16x16 hero-sized crate — scale2x of the classic
    // 8x8 art, emitted as 4 BG quadrant tiles (TL/TR/BL/BR).
    {
        let big = scale2x(&parse_grid(&grids::BGT_BLOCK));
        let tiles = sprite_to_tiles(&big, 16, 16);
        for (i, suffix) in ["tl", "tr", "bl", "br"].iter().enumerate() {
            let _ = writeln!(o, "{}", emit_tile_c_array(
                &format!("bgt_block16_{suffix}"), &tile_2bpp_bytes(&tiles[i])));
        }
    }

    // Mini-boss Sentinel (16x16)
    {
        let grid = parse_grid(&grids::BOSS_SENTINEL);
        let tiles = sprite_to_tiles(&grid, 16, 16);
        let _ = writeln!(o, "{}", emit_metasprite_c_array("sprite_boss_sentinel", &tiles));
    }

    // Mini-boss variants: 2x-scaled enemy art, distinct silhouettes
    for (name, lines) in grids::MINIBOSS_SRC {
        let big = scale2x(&parse_grid(lines));
        let tiles = sprite_to_tiles(&big, 16, 16);
        let _ = writeln!(o, "{}", emit_metasprite_c_array(
            &format!("sprite_miniboss_{name}"), &tiles));
    }

    // Bruiser tier: heavy enemies rendered player-sized (16x16). 2x-scale
    // of the 8x8 art so size reads as threat, in the same chunky style.
    for (name, lines) in grids::BRUISER_SRC {
        let big = scale2x(&parse_grid(lines));
        let tiles = sprite_to_tiles(&big, 16, 16);
        let _ = writeln!(o, "{}", emit_metasprite_c_array(
            &format!("sprite_bruiser_{name}"), &tiles));
    }

    // Nine distinct 32x32 stage bosses (stage 0 is the Colossus)
    for (i, grid) in bosses::boss_stages().iter().enumerate() {
        let tiles = sprite_to_tiles(grid, 32, 32);
        let _ = writeln!(o, "{}", emit_metasprite_c_array(
            &format!("sprite_boss_stage{i}"), &tiles));
    }

    o
}

fn main() -> Result<()> {
    let args = Args::parse();
    let out = generate();
    match args.out.to_str() == Some("-") {
        true => print!("{out}"),
        false => {
            // Idempotent write: leave the mtime alone when nothing changed
            // so `make` doesn't rebuild the ROM for a no-op regen.
            let unchanged = std::fs::read_to_string(&args.out)
                .map(|cur| cur == out)
                .unwrap_or(false);
            match unchanged {
                true => eprintln!("quintra-assets: {} up to date", args.out.display()),
                false => {
                    std::fs::write(&args.out, &out)
                        .with_context(|| format!("write {}", args.out.display()))?;
                    eprintln!("quintra-assets: wrote {} ({} bytes)",
                        args.out.display(), out.len());
                }
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generator's output is pinned against the checked-in
    /// src/render/sprites_gen.c — any drift in grids, boss math, or
    /// emission formatting fails here instead of shipping silently.
    #[test]
    fn golden_matches_checked_in_sprites_gen_c() {
        let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../../..");
        let path = format!("{root}/src/render/sprites_gen.c");
        let checked_in = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read {path}: {e}"));
        assert_eq!(generate(), checked_in,
            "generator output differs from checked-in sprites_gen.c — \
             regenerate via `cargo run -p quintra-assets` and commit both");
    }

    #[test]
    fn boss_grids_are_exactly_32x32() {
        for (i, g) in bosses::boss_stages().iter().enumerate() {
            assert_eq!(g.len(), 32, "boss {i} height");
            assert!(g.iter().all(|r| r.len() == 32), "boss {i} width");
        }
    }

    #[test]
    fn tile_2bpp_low_and_high_planes() {
        // one row of pixel value 3 = both planes set; value 1 = low only
        let tile: Vec<Vec<u8>> = vec![
            vec![3; 8], vec![1; 8], vec![2; 8], vec![0; 8],
            vec![0; 8], vec![0; 8], vec![0; 8], vec![0; 8],
        ];
        let b = tile_2bpp_bytes(&tile);
        assert_eq!(&b[0..6], &[0xFF, 0xFF, 0xFF, 0x00, 0x00, 0xFF]);
    }
}
