//! quintra-assets — sprite/tile authoring pipeline.
//!
//! The ASCII grids in grids.rs and the parametric bosses in bosses.rs are
//! the pixel source of truth; this binary compiles them to GBDK 2bpp C
//! arrays and declarations (src/render/sprites_gen.c/.h). Ported from the retired
//! scripts/sprite_authoring.py — output is pinned byte-identical by the
//! golden test below.

use std::fmt::Write as _;
use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::Parser;

mod bosses;
mod gbc;
mod grids;

use gbc::{emit_metasprite_c_array, emit_tile_c_array, parse_grid, scale2x,
          sprite_to_tiles, tile_2bpp_bytes};

#[derive(Parser, Debug)]
#[command(name = "quintra-assets")]
struct Args {
    /// Output C file (use '-' for stdout)
    #[arg(long, default_value = "src/render/sprites_gen.c")]
    out: PathBuf,
    /// Output declaration header; ignored when --out is '-'
    #[arg(long, default_value = "src/render/sprites_gen.h")]
    header_out: PathBuf,
}

fn declaration(o: &mut String, name: &str, bytes: usize) {
    let _ = writeln!(o, "extern const u8 {name}[{bytes}];");
}

pub fn generate_header() -> String {
    let mut o = String::new();
    let _ = writeln!(o, "// Auto-generated by quintra-assets (tools/crates/quintra-assets) — do not edit by hand.");
    let _ = writeln!(o, "#ifndef QUINTRA_RENDER_SPRITES_GEN_H");
    let _ = writeln!(o, "#define QUINTRA_RENDER_SPRITES_GEN_H\n");
    let _ = writeln!(o, "#include \"core/types.h\"\n");
    let _ = writeln!(o, "// 16x16 player class metasprites");
    for (name, _) in grids::PLAYERS { declaration(&mut o, &format!("sprite_class_{name}"), 64); }
    let _ = writeln!(o, "\n// 8x8 enemy sprites");
    for (name, _) in grids::ENEMIES_8 { declaration(&mut o, &format!("sprite_enemy_{name}"), 16); }
    let _ = writeln!(o, "\n// 8x8 effects and village roles");
    for (name, _) in grids::FX_8 { declaration(&mut o, &format!("sprite_fx_{name}"), 16); }
    let _ = writeln!(o, "\n// 8x8 dungeon background tiles");
    for (name, _) in grids::DUNGEON_TILES { declaration(&mut o, &format!("bgt_{name}"), 16); }
    for suffix in ["tl", "tr", "bl", "br"] {
        declaration(&mut o, &format!("bgt_block16_{suffix}"), 16);
    }
    let _ = writeln!(o, "\n// 16x16 mini-boss and bruiser metasprites");
    declaration(&mut o, "sprite_boss_sentinel", 64);
    for (name, _) in grids::MINIBOSS_SRC { declaration(&mut o, &format!("sprite_miniboss_{name}"), 64); }
    for (name, _) in grids::BRUISER_SRC { declaration(&mut o, &format!("sprite_bruiser_{name}"), 64); }
    let _ = writeln!(o, "\n// Nine 32x32 stage bosses (9 * 16 tiles * 16 bytes)");
    declaration(&mut o, "sprite_boss_stages", 2304);
    let _ = writeln!(o, "\n#endif");
    o
}

pub fn generate() -> String {
    let mut o = String::new();

    let _ = writeln!(o, "// Auto-generated by quintra-assets (tools/crates/quintra-assets) — do not edit by hand.");
    let _ = writeln!(o, "// Glyph map: .=0 transparent, 1=light, 2=mid, 3=dark");
    let _ = writeln!(o);
    let _ = writeln!(o, "#pragma bank 2");
    let _ = writeln!(o);
    let _ = writeln!(o, "#include \"core/types.h\"");
    let _ = writeln!(o);

    // Players (16x16 = 4 tiles each; walk cycle is OAM flips at render time)
    for (name, lines) in grids::PLAYERS {
        let grid = parse_grid(lines);
        let tiles = sprite_to_tiles(&grid, grids::PLAYER_W, grids::PLAYER_H);
        let _ = writeln!(o, "{}", emit_metasprite_c_array(
            &format!("sprite_class_{name}"), &tiles));
    }

    // Enemies (8x8 = 1 tile; waddle is an OAM X-flip)
    for (name, lines) in grids::ENEMIES_8 {
        let grid = parse_grid(lines);
        let _ = writeln!(o, "{}", emit_tile_c_array(
            &format!("sprite_enemy_{name}"), &tile_2bpp_bytes(&grid)));
    }

    // FX sprites (8x8)
    for (name, lines) in grids::FX_8 {
        let grid = parse_grid(lines);
        let _ = writeln!(o, "{}", emit_tile_c_array(
            &format!("sprite_fx_{name}"), &tile_2bpp_bytes(&grid)));
    }

    // Dungeon BG tiles (8x8)
    for (name, lines) in grids::DUNGEON_TILES {
        let grid = parse_grid(lines);
        let _ = writeln!(o, "{}", emit_tile_c_array(
            &format!("bgt_{name}"), &tile_2bpp_bytes(&grid)));
    }

    // Pushable block: a 16x16 hero-sized crate — scale2x of the classic
    // 8x8 art, emitted as 4 BG quadrant tiles (TL/TR/BL/BR).
    {
        let big = scale2x(&parse_grid(&grids::BGT_BLOCK));
        let tiles = sprite_to_tiles(&big, 16, 16);
        for (i, suffix) in ["tl", "tr", "bl", "br"].iter().enumerate() {
            let _ = writeln!(o, "{}", emit_tile_c_array(
                &format!("bgt_block16_{suffix}"), &tile_2bpp_bytes(&tiles[i])));
        }
    }

    // Mini-boss Sentinel (16x16)
    {
        let grid = parse_grid(&grids::BOSS_SENTINEL);
        let tiles = sprite_to_tiles(&grid, 16, 16);
        let _ = writeln!(o, "{}", emit_metasprite_c_array("sprite_boss_sentinel", &tiles));
    }

    // Mini-boss variants: 2x-scaled enemy art, distinct silhouettes
    for (name, lines) in grids::MINIBOSS_SRC {
        let big = scale2x(&parse_grid(lines));
        let tiles = sprite_to_tiles(&big, 16, 16);
        let _ = writeln!(o, "{}", emit_metasprite_c_array(
            &format!("sprite_miniboss_{name}"), &tiles));
    }

    // Bruiser tier: heavy enemies rendered player-sized (16x16). 2x-scale
    // of the 8x8 art so size reads as threat, in the same chunky style.
    for (name, lines) in grids::BRUISER_SRC {
        let big = scale2x(&parse_grid(lines));
        let tiles = sprite_to_tiles(&big, 16, 16);
        let _ = writeln!(o, "{}", emit_metasprite_c_array(
            &format!("sprite_bruiser_{name}"), &tiles));
    }

    // One contiguous atlas avoids SDCC bank-local pointer relocation tables,
    // which collapsed every indexed boss pointer to stage 0 on cartridge.
    let mut boss_bytes = Vec::with_capacity(9 * 256);
    for grid in bosses::boss_stages() {
        let tiles = sprite_to_tiles(&grid, 32, 32);
        boss_bytes.extend(tiles.iter().flat_map(|t| tile_2bpp_bytes(t)));
    }
    let body = boss_bytes.iter().map(|b| format!("0x{b:02X}"))
        .collect::<Vec<_>>().join(", ");
    let _ = writeln!(o, "const u8 sprite_boss_stages[2304] = {{ {body} }};");

    o
}

fn main() -> Result<()> {
    let args = Args::parse();
    let out = generate();
    match args.out.to_str() == Some("-") {
        true => print!("{out}"),
        false => {
            // Idempotent writes leave mtimes alone, avoiding no-op ROM rebuilds.
            write_if_changed(&args.out, &out)?;
            write_if_changed(&args.header_out, &generate_header())?;
        }
    }
    Ok(())
}

fn write_if_changed(path: &std::path::Path, text: &str) -> Result<()> {
    if std::fs::read_to_string(path).map(|cur| cur == text).unwrap_or(false) {
        eprintln!("quintra-assets: {} up to date", path.display());
    } else {
        std::fs::write(path, text).with_context(|| format!("write {}", path.display()))?;
        eprintln!("quintra-assets: wrote {} ({} bytes)", path.display(), text.len());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The generator's output is pinned against the checked-in
    /// src/render/sprites_gen.c — any drift in grids, boss math, or
    /// emission formatting fails here instead of shipping silently.
    #[test]
    fn golden_matches_checked_in_sprites_gen_c() {
        let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../../..");
        let path = format!("{root}/src/render/sprites_gen.c");
        let checked_in = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read {path}: {e}"));
        assert_eq!(generate(), checked_in,
            "generator output differs from checked-in sprites_gen.c — \
             regenerate via `cargo run -p quintra-assets` and commit both");
    }

    #[test]
    fn golden_matches_checked_in_sprites_gen_h() {
        let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../../..");
        let path = format!("{root}/src/render/sprites_gen.h");
        let checked_in = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read {path}: {e}"));
        assert_eq!(generate_header(), checked_in,
            "generated declarations drifted — run `make gen` and commit both outputs");
    }

    #[test]
    fn every_generated_array_has_exactly_one_declaration() {
        let body = generate();
        let header = generate_header();
        for line in body.lines().filter(|line| line.starts_with("const u8 ")) {
            let name = line.split_whitespace().nth(2).unwrap().split('[').next().unwrap();
            assert_eq!(header.matches(&format!(" {name}[")).count(), 1,
                "{name} declaration count drifted");
        }
    }

    #[test]
    fn boss_grids_are_exactly_32x32() {
        for (i, g) in bosses::boss_stages().iter().enumerate() {
            assert_eq!(g.len(), 32, "boss {i} height");
            assert!(g.iter().all(|r| r.len() == 32), "boss {i} width");
        }
    }

    #[test]
    fn void_lord_has_a_real_crown_and_is_not_the_first_boss() {
        let stages = bosses::boss_stages();
        assert_ne!(stages[8], stages[0],
            "final Void Lord art collapsed to the stage-0 Colossus");
        let crown_pixels = stages[8][0..6].iter().flatten()
            .filter(|&&pixel| pixel != 0).count();
        assert!(crown_pixels >= 28,
            "Void Lord crown silhouette is too sparse: {crown_pixels} pixels");
    }

    #[test]
    fn tile_2bpp_low_and_high_planes() {
        // one row of pixel value 3 = both planes set; value 1 = low only
        let tile: Vec<Vec<u8>> = vec![
            vec![3; 8], vec![1; 8], vec![2; 8], vec![0; 8],
            vec![0; 8], vec![0; 8], vec![0; 8], vec![0; 8],
        ];
        let b = tile_2bpp_bytes(&tile);
        assert_eq!(&b[0..6], &[0xFF, 0xFF, 0xFF, 0x00, 0x00, 0xFF]);
    }

    #[test]
    fn village_roles_have_distinct_runtime_tiles() {
        let elder = tile_2bpp_bytes(&parse_grid(&grids::VILLAGER));
        let merchant = tile_2bpp_bytes(&parse_grid(&grids::MERCHANT));
        let smith = tile_2bpp_bytes(&parse_grid(&grids::SMITH));
        let apothecary = tile_2bpp_bytes(&parse_grid(&grids::APOTHECARY));
        assert_ne!(smith, elder);
        assert_ne!(smith, merchant);
        assert_ne!(elder, merchant);
        assert_ne!(apothecary, elder);
        assert_ne!(apothecary, merchant);
        assert_ne!(apothecary, smith);
    }

    #[test]
    fn specialist_enemies_do_not_reuse_legacy_silhouettes() {
        let specialists = [
            tile_2bpp_bytes(&parse_grid(&grids::FOLD_STAR)),
            tile_2bpp_bytes(&parse_grid(&grids::FLUTTERBAT)),
            tile_2bpp_bytes(&parse_grid(&grids::GLOAM_LEECH)),
            tile_2bpp_bytes(&parse_grid(&grids::CINDER_MAW)),
            tile_2bpp_bytes(&parse_grid(&grids::RIFT_OOZE)),
        ];
        for i in 0..specialists.len() {
            for j in i + 1..specialists.len() {
                assert_ne!(specialists[i], specialists[j]);
            }
        }
        assert_ne!(specialists[0], tile_2bpp_bytes(&parse_grid(&grids::SHADE)));
        assert_ne!(specialists[1], tile_2bpp_bytes(&parse_grid(&grids::HORNET)));
        assert_ne!(specialists[2], tile_2bpp_bytes(&parse_grid(&grids::WISP)));
        assert_ne!(specialists[3], tile_2bpp_bytes(&parse_grid(&grids::CRAWLER)));
    }
}
