#!/usr/bin/env python3
"""Apply data-driven arena tile→palette tables into build_v301_teleport.py.

Parses PYDICT lines emitted by /tmp/probe_all_tables.lua (one per boss,
keyed by name) and rewrites each `_bg_table_<boss>()` builder to use the
measured tile→palette dict instead of guessed contiguous ranges.

The measured dicts are written into a generated module
`scripts/arena_tables_data.py` that build_v301_teleport.py imports, so the
big literals live in one place and the builder stays readable.

Usage:  python scripts/apply_arena_tables.py /tmp/all_tables.log
"""
import re
import sys
from pathlib import Path

NAME_ORDER = [
    "shalamar", "riff", "crystal_dragon", "cameo", "ted",
    "troop", "faze", "angela", "penta_dragon",
]


def parse_log(path: Path) -> dict:
    """name -> {tile_id: palette}."""
    out = {}
    for line in path.read_text().splitlines():
        m = re.match(r"PYDICT (\w+) \{(.*)\}", line.strip())
        if not m:
            continue
        name, body = m.group(1), m.group(2).strip()
        d = {}
        if body:
            for pair in body.split(","):
                k, v = pair.split(":")
                d[int(k.strip(), 16)] = int(v.strip())
        out[name] = d
    return out


def emit_data_module(tables: dict, out_path: Path) -> None:
    lines = [
        '"""Data-driven arena tile→palette tables (GENERATED).',
        "",
        "Generated by scripts/apply_arena_tables.py from a 360-frame animation",
        "tour (scripts/probe_all_tables.lua). Each entry maps a boss BG tile ID",
        "to a CGB BG palette index, bucketed by the tile's mean screen row over",
        "the animation cycle (quartile bands: top→4, upper-mid→6, lower-mid→5,",
        "bottom→3). Tile-ID keyed ⇒ animation-stable + bob-proof.",
        "",
        "Regenerate: python scripts/apply_arena_tables.py /tmp/all_tables.log",
        '"""',
        "",
        "ARENA_TILE_PAL = {",
    ]
    for name in NAME_ORDER:
        d = tables.get(name)
        if not d:
            lines.append(f"    {name!r}: {{}},  # NO DATA (probe missed this boss)")
            continue
        items = ", ".join(f"0x{t:02X}: {p}" for t, p in sorted(d.items()))
        lines.append(f"    {name!r}: {{{items}}},")
    lines.append("}")
    out_path.write_text("\n".join(lines) + "\n")


def main():
    logs = [Path(p) for p in sys.argv[1:]] or [Path("/tmp/all_tables.log")]
    tables = {}
    for log in logs:
        if not log.exists():
            print(f"  (skip missing {log})")
            continue
        part = parse_log(log)
        # Later logs override earlier (re-probes win), but only with non-empty.
        for name, d in part.items():
            if d:
                tables[name] = d
    print(f"Parsed tables from {len(logs)} log(s):")
    for name in NAME_ORDER:
        d = tables.get(name, {})
        print(f"  {name:16s} {len(d):3d} tiles")
    out = Path(__file__).parent / "arena_tables_data.py"
    emit_data_module(tables, out)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
