#!/usr/bin/env python3
"""Live palette editor — browser-based GUI for tuning Penta Dragon DX CGB colors.

Workflow:
  1. Start this script:  python3 scripts/live_palette_editor.py
  2. Open http://localhost:8077 in browser
  3. Launch mGBA with live palette script:
       mgba-qt rom/working/penta_dragon_dx_v301.gb --script scripts/lua/live_palettes.lua
  4. Adjust colors in browser. Changes apply to running game within ~0.5s.

The browser saves color picks to /tmp/live_palettes.txt. The mGBA Lua
script polls that file every 30 frames (~0.5s) and rewrites CGB palette
CRAM (BCPS/BCPD for BG, OCPS/OCPD for OBJ) with the new values.

To persist tuned colors back to the YAML, click "Save to YAML" — appends
the current state to palettes/penta_palettes_v097.yaml.

Color format in /tmp/live_palettes.txt:
  BG<n>:<idx>=<hex>,<idx>=<hex>,...
  OBJ<n>:<idx>=<hex>,<idx>=<hex>,...
where <hex> is 4-char BGR555 (e.g. "7FFF") or 6-char RGB hex.

Default palettes are loaded from palettes/penta_palettes_v097.yaml.
"""
import http.server
import json
import socketserver
import threading
import time
import re
import sys
from pathlib import Path
from urllib.parse import parse_qs, urlparse

try:
    import yaml
except ImportError:
    print("Install: pip install pyyaml")
    sys.exit(1)

ROOT = Path(__file__).parent.parent
LIVE_FILE = Path("/tmp/live_palettes.txt")
YAML_PATH = ROOT / "palettes" / "penta_palettes_v097.yaml"

PORT = 8077

# Stage boss metadata.
# FFBF values 1-2 are miniboss (Gargoyle/Spider) — excluded.
# FFBF values 3-8 are stage bosses. Each maps to an OBJ palette slot
# via the boss_slot_table at bank 13:0x68C0 = [6,7,6,7,6,7,4,5].
STAGE_BOSSES = [
    # (FFBF value, label, OBJ slot, arena D880 value, YAML key)
    (3, "Boss 3 — Crimson",   6, 0x0C, "Boss3_Crimson"),
    (4, "Boss 4 — Ice",       7, 0x0D, "Boss4_Ice"),
    (5, "Boss 5 — Void",      6, 0x0E, "Boss5_Void"),
    (6, "Boss 6 — Poison",    7, 0x0F, "Boss6_Poison"),
    (7, "Boss 7 — Knight",    4, 0x12, "Boss7_Knight"),
    (8, "Boss 8 — Angela",    5, 0x14, "Angela"),
]


def bgr555_to_rgb888(val15: int) -> str:
    r5 = val15 & 0x1F
    g5 = (val15 >> 5) & 0x1F
    b5 = (val15 >> 10) & 0x1F
    r = (r5 * 255) // 31
    g = (g5 * 255) // 31
    b = (b5 * 255) // 31
    return f"#{r:02x}{g:02x}{b:02x}"


def rgb888_to_bgr555(rgb_hex: str) -> int:
    s = rgb_hex.lstrip("#")
    r = int(s[0:2], 16) if len(s) >= 6 else 0
    g = int(s[2:4], 16) if len(s) >= 6 else 0
    b = int(s[4:6], 16) if len(s) >= 6 else 0
    r5 = min(31, (r * 31) // 255)
    g5 = min(31, (g * 31) // 255)
    b5 = min(31, (b * 31) // 255)
    return (b5 << 10) | (g5 << 5) | r5


def load_yaml_palettes() -> dict:
    """Returns {kind: {pal_idx: [color_hex × 4]}}."""
    with open(YAML_PATH) as f:
        data = yaml.safe_load(f)
    bg_keys = ['Dungeon', 'BG1', 'BG2', 'BG3', 'BG4', 'BG5', 'BG6', 'BG7']
    obj_keys = ['EnemyProjectile', 'SaraDragon', 'SaraWitch',
                'SaraProjectileAndCrow', 'Hornets', 'OrcGround',
                'Humanoid', 'Catfish']
    palettes = {"BG": {}, "OBJ": {}, "BOSS": {}}
    for i, k in enumerate(bg_keys):
        entry = data.get('bg_palettes', {}).get(k, {})
        palettes["BG"][i] = entry.get('colors', ["7FFF", "5294", "2108", "0000"])
    for i, k in enumerate(obj_keys):
        entry = data.get('obj_palettes', {}).get(k, {})
        palettes["OBJ"][i] = entry.get('colors', ["0000", "7C1F", "4C0F", "0000"])
    # Stage boss palettes from boss_palettes YAML key
    for ffbf, label, slot, d880, yaml_key in STAGE_BOSSES:
        entry = data.get('boss_palettes', {}).get(yaml_key, {})
        palettes["BOSS"][ffbf] = entry.get('colors', ["0000", "7C1F", "4C0F", "0000"])
    palettes["BG_labels"] = bg_keys
    palettes["OBJ_labels"] = obj_keys
    return palettes


def write_live_file(state: dict, preview_ffbf: int = 0, teleport: dict = None):
    """Write the current state dict to LIVE_FILE in mGBA-readable format.

    Optional `preview_ffbf`: if non-zero, forces FFBF to this value so the
    boss palette code path runs every frame (game's palette_loader writes
    boss_pal data to OBJ slot, then we re-override with user's colors).

    Optional `teleport`: dict with keys 'ffba', 'd880' if user requested
    a teleport. Lua applies once then clears via a sentinel.
    """
    lines = ["# Auto-generated by live_palette_editor.py"]
    for kind in ("BG", "OBJ"):
        for pal_idx, colors in state[kind].items():
            entries = ",".join(f"{ci}={c.upper()}" for ci, c in enumerate(colors))
            lines.append(f"{kind}{pal_idx}:{entries}")
    # Boss palette: write to the OBJ slot that the boss occupies.
    # Only emit when preview_ffbf matches this boss (otherwise the OBJ
    # slot colors come from the standard OBJ palette line above).
    if preview_ffbf:
        for ffbf, label, slot, d880, yaml_key in STAGE_BOSSES:
            if ffbf == preview_ffbf:
                colors = state["BOSS"].get(ffbf, ["0000"] * 4)
                entries = ",".join(f"{ci}={c.upper()}" for ci, c in enumerate(colors))
                # Override OBJ slot for this boss
                lines.append(f"# Boss preview: FFBF={ffbf} ({label}) → OBJ slot {slot}")
                lines.append(f"OBJ{slot}:{entries}")
                lines.append(f"FFBF:{ffbf}")
                break
    if teleport:
        if "ffba" in teleport:
            lines.append(f"FFBA:{teleport['ffba']}")
        if "d880" in teleport:
            lines.append(f"D880:0x{teleport['d880']:02X}")
        if "ffbf" in teleport:
            lines.append(f"FFBF:{teleport['ffbf']}")
        if "ffb7" in teleport:
            lines.append(f"FFB7:0x{teleport['ffb7']:02X}")
        lines.append("TELEPORT:1")  # one-shot trigger
    LIVE_FILE.write_text("\n".join(lines) + "\n")


# Global state
STATE = load_yaml_palettes()
PREVIEW_FFBF = 0  # 0 = no preview, 3..8 = preview this boss
write_live_file(STATE)


def render_index():
    """Generate HTML page with palette pickers."""
    html_parts = ["""<!DOCTYPE html>
<html><head><title>Penta Dragon DX Live Palette</title>
<style>
body { font-family: sans-serif; background: #1a1a1a; color: #eee; padding: 1em; }
h1 { margin: 0 0 0.5em 0; }
.section { margin-bottom: 1.5em; }
.pal { display: inline-block; margin: 0.5em 1em 0.5em 0; vertical-align: top; }
.pal-name { font-size: 0.9em; margin-bottom: 0.3em; color: #aaa; }
.color { display: inline-block; width: 32px; height: 32px; margin: 0 2px;
         border: 1px solid #555; cursor: pointer; }
.color-row { display: flex; }
input[type=color] { width: 32px; height: 32px; padding: 0; border: 0;
                    background: transparent; cursor: pointer; }
button { padding: 0.5em 1em; margin: 0.3em; background: #444;
         color: #eee; border: 1px solid #666; cursor: pointer; }
button:hover { background: #666; }
.preset { display: inline-block; padding: 0.3em 0.5em;
          background: #2a4; color: white; cursor: pointer; margin-right: 0.3em; }
.bgr { font-family: monospace; font-size: 0.75em; color: #888;
       margin-top: 0.2em; min-width: 32px; display: inline-block; }
</style></head><body>
<h1>Penta Dragon DX — Live Palette Editor</h1>
<p>Edits apply to running mGBA within ~0.5s.
Make sure mGBA was launched with <code>--script scripts/lua/live_palettes.lua</code>.</p>
<button onclick="reload()">Reload from YAML</button>
<button onclick="save()">Save to YAML</button>
<button onclick="copyState()">Copy current as JSON</button>
"""]

    # Boss palette section — stage bosses (FFBF 3-8). Each has its own
    # color set + a "preview" radio to force FFBF live + a "teleport"
    # button to set FFBA/D880/FFB7.
    html_parts.append('<div class="section"><h2>Stage Boss Palettes (FFBF 3-8)</h2>')
    html_parts.append('<p style="font-size:0.85em;color:#888;">'
                      'Pick a boss to <em>preview</em> live (forces FFBF every frame so the game writes boss palette to its OBJ slot, then your color picks override). '
                      'Or click <em>Teleport</em> to write FFBA/D880/FFB7 once. Teleport is best-effort — boss tile data may not load fully without proper arena init.</p>')
    html_parts.append(f'<div><label><input type="radio" name="preview" value="0" {"checked" if PREVIEW_FFBF == 0 else ""} onchange="setPreview(0)"> No preview</label></div>')
    for ffbf, label, slot, d880, yaml_key in STAGE_BOSSES:
        colors = STATE["BOSS"].get(ffbf, ["0000"] * 4)
        checked = "checked" if PREVIEW_FFBF == ffbf else ""
        html_parts.append(f'<div class="pal" style="display:block;margin:0.5em 0;">')
        html_parts.append(f'<div style="display:flex;align-items:center;gap:0.5em;">')
        html_parts.append(f'<label><input type="radio" name="preview" value="{ffbf}" {checked} onchange="setPreview({ffbf})"> Preview</label>')
        html_parts.append(f'<button onclick="teleport({ffbf}, 0x{d880:02X})">Teleport</button>')
        html_parts.append(f'<span class="pal-name">{label} (FFBF={ffbf}, OBJ slot {slot}, arena D880=0x{d880:02X})</span>')
        html_parts.append(f'</div>')
        html_parts.append('<div class="color-row" style="margin-top:0.3em;">')
        for ci, c in enumerate(colors):
            val15 = int(c, 16)
            rgb = bgr555_to_rgb888(val15)
            html_parts.append(
                f'<div><input type="color" value="{rgb}" '
                f'data-kind="BOSS" data-pal="{ffbf}" data-color="{ci}" '
                f'onchange="updateColor(this)">'
                f'<div class="bgr" id="bgr-BOSS-{ffbf}-{ci}">{c.upper()}</div></div>'
            )
        html_parts.append("</div></div>")
    html_parts.append("</div>")

    for kind in ("BG", "OBJ"):
        labels = STATE.get(kind + "_labels", [f"{kind}{i}" for i in range(8)])
        html_parts.append(f'<div class="section"><h2>{kind} Palettes</h2>')
        for pal_idx in range(8):
            colors = STATE[kind].get(pal_idx, ["0000"] * 4)
            label = labels[pal_idx]
            html_parts.append(f'<div class="pal"><div class="pal-name">{kind}{pal_idx}: {label}</div><div class="color-row">')
            for ci, c in enumerate(colors):
                val15 = int(c, 16)
                rgb = bgr555_to_rgb888(val15)
                html_parts.append(
                    f'<div><input type="color" value="{rgb}" '
                    f'data-kind="{kind}" data-pal="{pal_idx}" data-color="{ci}" '
                    f'onchange="updateColor(this)">'
                    f'<div class="bgr" id="bgr-{kind}-{pal_idx}-{ci}">{c.upper()}</div></div>'
                )
            html_parts.append("</div></div>")
        html_parts.append("</div>")

    html_parts.append("""
<script>
function rgb888_to_bgr555(rgb) {
    const s = rgb.replace('#', '');
    const r = parseInt(s.substr(0, 2), 16);
    const g = parseInt(s.substr(2, 2), 16);
    const b = parseInt(s.substr(4, 2), 16);
    const r5 = Math.min(31, Math.floor(r * 31 / 255));
    const g5 = Math.min(31, Math.floor(g * 31 / 255));
    const b5 = Math.min(31, Math.floor(b * 31 / 255));
    return ((b5 << 10) | (g5 << 5) | r5).toString(16).padStart(4, '0').toUpperCase();
}
function updateColor(input) {
    const kind = input.dataset.kind;
    const pal = parseInt(input.dataset.pal);
    const color = parseInt(input.dataset.color);
    const bgr = rgb888_to_bgr555(input.value);
    document.getElementById(`bgr-${kind}-${pal}-${color}`).textContent = bgr;
    fetch('/update', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({kind, pal, color, bgr})
    });
}
function setPreview(ffbf) {
    fetch('/preview', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({ffbf})
    });
}
function teleport(ffbf, d880) {
    // FFBA = boss index (ffbf - 1)? Actually FFBA is level counter
    // which differs from FFBF. Let's pass d880 + ffbf and let server
    // figure out FFBA mapping.
    fetch('/teleport', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({ffbf, d880})
    }).then(r => r.text()).then(t => console.log('teleport:', t));
}
function reload() {
    fetch('/reload', {method: 'POST'}).then(() => location.reload());
}
function save() {
    fetch('/save', {method: 'POST'}).then(r => r.text()).then(t => alert(t));
}
function copyState() {
    fetch('/state').then(r => r.text()).then(t => {
        navigator.clipboard.writeText(t);
        alert("State copied to clipboard");
    });
}
</script>
</body></html>""")
    return "\n".join(html_parts)


class Handler(http.server.BaseHTTPRequestHandler):
    def log_message(self, format, *args):
        pass  # silence default logging

    def do_GET(self):
        url = urlparse(self.path)
        if url.path == "/" or url.path == "/index.html":
            body = render_index().encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        elif url.path == "/state":
            body = json.dumps(STATE, indent=2).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        global STATE, PREVIEW_FFBF
        url = urlparse(self.path)
        length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(length).decode("utf-8") if length > 0 else ""
        if url.path == "/update":
            try:
                data = json.loads(body)
                kind = data["kind"]
                pal = int(data["pal"])
                color = int(data["color"])
                bgr = data["bgr"].upper()
                STATE[kind][pal][color] = bgr
                write_live_file(STATE, preview_ffbf=PREVIEW_FFBF)
                self.send_response(200)
                self.end_headers()
            except Exception as e:
                self.send_response(400)
                self.end_headers()
                self.wfile.write(f"error: {e}".encode())
        elif url.path == "/preview":
            try:
                data = json.loads(body)
                PREVIEW_FFBF = int(data.get("ffbf", 0))
                write_live_file(STATE, preview_ffbf=PREVIEW_FFBF)
                self.send_response(200)
                self.end_headers()
            except Exception as e:
                self.send_response(400)
                self.end_headers()
                self.wfile.write(f"error: {e}".encode())
        elif url.path == "/teleport":
            try:
                data = json.loads(body)
                ffbf = int(data.get("ffbf", 0))
                d880 = int(data.get("d880", 0))
                # FFBA = boss-index for the stage-boss dispatch table.
                # Stage boss FFBF=3..8 map to FFBA values 0..7 (per arena
                # jump table at bank 2:0x6EA6 — first 2 entries are 0xC0..)
                # Best guess: FFBA = ffbf - 1 (but might need ffbf - 3).
                # Try ffbf - 1 first; user can manually adjust if wrong.
                ffba = ffbf - 1 if ffbf > 0 else 0
                teleport = {
                    "ffba": ffba,
                    "d880": d880,
                    "ffbf": ffbf,
                    "ffb7": d880,
                }
                write_live_file(STATE, preview_ffbf=PREVIEW_FFBF, teleport=teleport)
                self.send_response(200)
                self.send_header("Content-Type", "text/plain")
                self.end_headers()
                self.wfile.write(f"teleport requested: FFBA={ffba}, D880=0x{d880:02X}, FFBF={ffbf}".encode())
            except Exception as e:
                self.send_response(400)
                self.end_headers()
                self.wfile.write(f"error: {e}".encode())
        elif url.path == "/reload":
            STATE = load_yaml_palettes()
            write_live_file(STATE, preview_ffbf=PREVIEW_FFBF)
            self.send_response(200)
            self.end_headers()
        elif url.path == "/save":
            self.save_to_yaml()
            self.send_response(200)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(f"Saved to {YAML_PATH}".encode())
        else:
            self.send_response(404)
            self.end_headers()

    def save_to_yaml(self):
        """Update the YAML file with current STATE colors."""
        with open(YAML_PATH) as f:
            data = yaml.safe_load(f)
        bg_keys = STATE.get("BG_labels", [])
        obj_keys = STATE.get("OBJ_labels", [])
        for i, k in enumerate(bg_keys):
            if k in data.get('bg_palettes', {}):
                data['bg_palettes'][k]['colors'] = STATE["BG"][i]
        for i, k in enumerate(obj_keys):
            if k in data.get('obj_palettes', {}):
                data['obj_palettes'][k]['colors'] = STATE["OBJ"][i]
        # Boss palettes
        for ffbf, label, slot, d880, yaml_key in STAGE_BOSSES:
            if yaml_key in data.get('boss_palettes', {}):
                data['boss_palettes'][yaml_key]['colors'] = STATE["BOSS"][ffbf]
        with open(YAML_PATH, "w") as f:
            yaml.safe_dump(data, f, default_flow_style=None)


def main():
    print(f"Live palette editor")
    print(f"  Browser: http://localhost:{PORT}")
    print(f"  mGBA Lua script: scripts/lua/live_palettes.lua")
    print(f"  Live file: {LIVE_FILE}")
    print(f"  YAML source: {YAML_PATH}")
    print()
    print(f"To launch mGBA with live update:")
    print(f"  mgba-qt rom/working/penta_dragon_dx_v301.gb \\")
    print(f"    --script scripts/lua/live_palettes.lua")
    print()
    with socketserver.TCPServer(("", PORT), Handler) as srv:
        srv.allow_reuse_address = True
        try:
            srv.serve_forever()
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    main()
